name: "LRA Crisis Tracker"
description: "LRA Crisis Tracker Security Briefs"
url: "http://localhost:4000"
baseurl: ""
permalink: /:categories/:title/
redirects: yes
encoding: "utf-8"
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor']